### ISSUE TITLE
FR4. User information library on backend

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#11]
Goal: Contains all information needed by the website to utilize within user interactions
Stakeholders: Backend web server
Description: The user information library will contain information needed by the website to authenticate user login information, retain user login details such as passwords and usernames, keep track of goals, keep track of challenges, and keep track of login streaks. This library will also contain and keep track of when/if the user wishes to change login information and will be able to add or remove profiles.
Origin: Based on initial project speculation, team came up with feature during initial meetings
Version: 1.0
Date: 1/23/2024
Priority: 1

**Comment by JesseNaser** [comment]
#49 The functions utilize their own structures within Cloudflare KV (key-value) store, with custom JSON formatting, and with Cloudflare D1 (database), for tables. All accounts and their information are kept track in these storage mechanisms. They are implemented and documented in #49
