### ISSUE TITLE
FR5. Goal tracking

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#12]
Goal: Enables users to set and track personal goals to manage burnout and stress.
Stakeholders: Users
Description: A goal tracker will be made that will enable users to create and track new wellness goals or track pre-made ones. There will be specific details such as goal name, a description of the goal, and a set completion date.
Origin: Based on initial project speculation, team came up with feature during initial meetings.
Version: 1.0
Date: 1/26/2024
Priority: 2

**Comment by JesseNaser** [comment]
Goal tracking implemented in #43 . Users can track their goals with a description, due date, category, priority, status (for saving old goals) and different views of their goals.
