### ISSUE TITLE
FR8. Daily and weekly login challenges

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#15]
Goal: Unique challenges available weekly that will help with stress relief and relaxation
Stakeholders: Users
Description: This feature comprises various weekly and daily challenges, that encourage users to take some time to de-stress and relax, in order to better their mental-health. There will be at least 1 daily challenge (which will refresh daily), and 1 weekly challenge (which will refresh weekly). Both challenges will require the user to confirm when they have completed them.
Origin: Based on initial project speculation, team came up with feature during initial meetings.
Version: 1.0
Date: 1/29/2024
Priority: 3

**Comment by JesseNaser** [comment]
#47 Implements this. The user made challenge that has the most active users is the weekly, the second most is the daily. When active users leave, it makes space for new challenges to rise.
