### ISSUE TITLE
FR9. Login streak tracker

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#16]
Goal: Display a counter pertaining to how many days in a row the user logged into the website
Stakeholders: Users
Description: A streak showing how many days in a row the user has returned to the website and participated in any of the various activities:
- Meetup post or confirmation
- Forum post
- Daily challenge
- Weekly challenge 
This streak will be displayed on both the progress/account dashboard, and the user profile page.
Origin: Based on initial project speculation, team came up with feature during initial meetings.
Version: 1.0
Date: 1/29/2024
Priority: 3

**Comment by JesseNaser** [comment]
#46 Implemented at /leaderboard
