### ISSUE TITLE
FR10. Community sharing forum

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#17]
Goal: A forum where users can share their favorite mindful break routines, experiences, and tips
Stakeholders: Users
Description: The community sharing forum will require a form of forum, through which users can create posts, click-into other users’ posts, and comment on other users’ posts. This will require a way to display users’ posts, a way to automatically generate user posts when they wish to make a post, and a way to automatically generate comments when users want to comment. It will also require a way to display comments and the content of a given post, as well as a brief description of a user’s post on the main forum page.

- Main forum page with
-  users posts
- Comments

Origin: Based on initial project speculation, team members came up with this idea during initial meetings.
Version: 1.0
Date: 1/23/2024
Priority: 2

**Comment by JesseNaser** [comment]
Implemented:
- Users can create posts topics
- Users can click on users post topics
- Users can comment on other users post topics.

- All open topics are rendered.
- All comments in a topic are rendered.

Done and resolved from #41
