### ISSUE TITLE
FR11. Community meetup post forum

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#18]
Goal: A forum where users can create posts inviting others to meetups at Wayne State
Stakeholders: Users
Description: The community meetup forum will require a form of forum, through which users can create posts displaying meetup information to other users, click-into other users’ posts, and confirm their intention to meet or not.. This will require similar features in accordance with the general forum, and will also require a way to display user meetup information, such as time and location.

- Main meetup forum page
- User meetup posts
- Confirmation of meeting

Origin: Based on initial project speculation, team members came up with this idea during initial meetings.
Version: 1.0
Date: 1/29/2024
Priority: 2

**Comment by JesseNaser** [comment]
#106 Done.
