### ISSUE TITLE
FR12. Progress/account dashboard

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#19]
Goal: Provide users with a comprehensive Progress/Account dashboard.
Stakeholders: Users
Description: A dedicated dashboard that allows users to track their overall progress, view completed goals, monitor wellness achievements, and access personalized insights. The dashboard should provide a user-friendly interface for a holistic overview of their wellness journey on the platform.
Origin: Based on initial project speculation, the team identified this feature during initial meetings.
Version: 1.0
Date: 1/29/2024
Priority: 2

**Comment by DeboshreeChowdhury** [comment]
Progress dashboard feature could not be completed due to time constraints. This feature requires additional development and integration with backend services for data tracking and visualization.

**Comment by JesseNaser** [comment]
#48 Implemented account and progress dashboard. Can see user created challenges, including weekly and daily challenge. Account Config, Login Streak Leaderboard, and Personal Goal Tracker.
