### ISSUE TITLE
NFR1.Appealing visual style

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#2]
**Goal**: Create a visually appealing style for the website
Stakeholder: Users
**Description**: Create a simple and easy-to-read visual style that does not conflict with the layout or draw attention away from important user-interface aspects. This will allow the website to have an appealing color palette and visual style, as well as being consistent across web pages.
**Origin**: Based on recent project meetings, team came up with feature during feature meetings
**Version**:1.0
**Date:01/29/2024
Priority:**1

**Comment by JesseNaser** [comment]
#82 All pages have been Bootstrapped formatted.
