### ISSUE TITLE
FR14. Customizable User Profiles 

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#21]
Goal: Allow users to personalize their profiles with preferences and settings.
Stakeholders: Users
Description: Enable users to customize their profiles by adding personal preferences, setting notification preferences, and adjusting other settings to enhance their overall experience on the platform.
Origin:  Based on initial project speculation, team came up with feature during initial meetings
Version: 1.0
Date: 1/29/2024
Priority: 1

**Comment by JesseNaser** [comment]
#45 Fully Customizable User Profiles implemented in /config:
- Update profile pronouns and name
- Update email and add multiple emails (for software engineers matching to company groups)
- Manage active sessions and remove them for security
