### ISSUE TITLE
FR15. Wellness Challenges 

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#22]
Goal: Engage users in wellness challenges for motivation.
Stakeholders: Users
Description: Create a feature that introduces wellness challenges for users to participate in, encouraging them to adopt and track healthy habits. Challenges could include daily tasks, mindfulness exercises, and stress-relief activities.
Origin:  Based on initial project speculation, team came up with feature during initial meetings
Version: 1.0
Date: 1/29/2024
Priority: 1

**Comment by DeboshreeChowdhury** [comment]
Issue closed. The Wellness Challenges Page is up and running. It offers  simple and fun activities to help everyone relax and feel good. Users can try different challenges to take a break from work. Each challenge has its own timer.

**Comment by JesseNaser** [comment]
In addition to the site generated challenges, #44 implements user generated challenges with completion and logs to show between the users.
