### ISSUE TITLE
FR16. User Profile Storage 

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#23]
Goal: A general use user profile structure
Stakeholders: Users
Description: Create a user class that stores various forms of information about the user that is used by the website (below information is only tentative, may be more information needed):

- Username
- Password
- Name
- Email
- Login streaks

Origin:  Based on later project progress, realized needed a centralized form of user profile storage.
Version: 1.0
Date: 1/29/2024
Priority: 1

**Comment by JesseNaser** [comment]
User profile storage covers usernames, passwords with salting, name first and last, email(s), and now implements login streaks directly in the log-in flow.

Resolved from #42
