### ISSUE TITLE
NFR2. Simple navigation

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#3]
**Goal:** Create an easy-to-navigate website for the user
Stakeholders: Users
**Description:** Keep links visually clear and indicate clearly to users where links and pages will take them, as well as general descriptors for various links and pages.
**Origin:** Based on recent project meetings, team came up with feature during feature meetings
**Version:** 1.0
**Date:** 1/23/2024
**Priority:** 1

**Comment by JesseNaser** [comment]
#82 Every userpage has login/signout/account/user buttons on the top. All of the navigation is uniform and working between pages and formatted.
