### ISSUE TITLE
[BUG] Unable to Retrieve Posts from Cloudflare KV Namespace

### ISSUE THREAD

**Issue by NoahMousseau** [WSU-4110/Stress-and-Burnout-Reduction#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The forum.js script is unable to be used to retrieve posts from the Cloudflare KV namespace coolfrog.forum and display them to either forum.html or meetup.html.

### Expected Behavior

The forum.js script should retrieve the posts in json format from Cloudflare, convert them to usable string arrays, and then iterate through the arrays and display each post on its respective forum.

**Comment by JesseNaser** [comment]
This issue has been solved by pull request #40
