### ISSUE TITLE
NFR3. Organized layout

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#4]
**Goal:** Ensure an organized layout for the website
**Stakeholders:** Users
**Description:** Implement a clear and structured layout that enhances the user experience. This includes logically organizing content, providing intuitive navigation, and maintaining consistency in design elements across web pages. An organized layout contributes to a seamless and efficient interaction with the website.
**Origin:** Based on recent project meetings, the team identified this requirement during feature meetings.
**Version:** 1.0
**Date:** 1/29/2024
**Priority:** 2

**Comment by JesseNaser** [comment]
#82
- All of the GitHub repo is sorted into descriptive folders and files are placed in right locations
- Navigation bar logically orders content. All other content for the user is on their account page with links.
- All pages consistently show the user login/logout/account flow so the user always can access their account.
