### ISSUE TITLE
NFR5. Performance

### ISSUE THREAD

**Issue by DeboshreeChowdhury** [WSU-4110/Stress-and-Burnout-Reduction#6]
**Goal:** Produce a well performing website with average to above average load times
**Stakeholders:** Users
**Description:** This can be achieved by minimizing the size of images and other media files and using efficient coding practices.
**Origin:** Based on recent project meetings, team came up with feature during feature meetings
**Version:** 1.0
**Date:** 1/23/2024
**Priority:** 1

**Comment by JesseNaser** [comment]
The website is fully serverless running on Cloudflare, and is blazing fast from Cloudflare.

See installation.md for the description on this design.
